# Generated by Django 4.2 on 2023-04-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('ward_num', models.IntegerField()),
                ('contact_num', models.IntegerField()),
                ('cows', models.IntegerField()),
                ('buffaloes', models.IntegerField()),
                ('total_milk_produced', models.IntegerField()),
                ('balance_milk_remaining', models.IntegerField()),
                ('selling_to_sudha', models.BooleanField()),
                ('selling_to_other_whom', models.CharField(max_length=50)),
                ('selling_to_other_rate', models.CharField(max_length=50)),
                ('village_code', models.IntegerField()),
            ],
        ),
    ]
