# Generated by Django 4.1.2 on 2023-04-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memdcs', '0002_additionaldetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_code', models.IntegerField()),
                ('village_name', models.CharField(max_length=50)),
                ('panchayat_code', models.IntegerField()),
                ('panchayat_name', models.CharField(max_length=50)),
                ('block_code', models.IntegerField()),
                ('block_name', models.CharField(max_length=50)),
                ('district_code', models.IntegerField()),
                ('district_name', models.CharField(max_length=50)),
                ('state_code', models.IntegerField()),
                ('state_name', models.CharField(max_length=50)),
            ],
        ),
    ]
